[package]
name = "janus-plugin-sys"
version = "0.1.0"
authors = ["Marshall Quander <marshall@quander.me>"]
description = "Native bindings to the Janus plugin API."

[dependencies]
glib-sys = "0.4.0"
jansson-sys = { path = "../jansson-sys" }
