[package]
name = "janus-plugin"
version = "0.1.0"
authors = ["Marshall Quander <marshall@quander.me>"]
description = "Rust bindings for creating Janus plugins."

[dependencies]
janus-plugin-sys = { path = "janus-plugin-sys", version = "0.1.0" }