[package]
name = "janus-plugin"
version = "0.1.0"
authors = ["Marshall Quander <marshall@quander.me>"]
description = "Library for creating plugins for Janus, the WebRTC gateway."
license = "MPL-2.0"

[workspace]
members = ["janus-plugin-sys", "jansson-sys"]

[dependencies]
chrono = "0.4"
colored = "1.5"
cstr-macro = "0.1"
glib-sys = "0.4"
libc = "0.2"
jansson-sys = { path = "jansson-sys" }
janus-plugin-sys = { path = "janus-plugin-sys" }