[package]
name = "jansson-sys"
version = "0.1.0"
authors = ["Marshall Quander <marshall@quander.me>"]
description = "Native bindings for Jansson, the C JSON library."

[dev-dependencies]
cstr-macro = "0.1.0"